project:
  type: website

website:
  title: "William R. P. Conti"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: ensino.qmd
        text: Ensino

      - href: pesquisa.qmd
        text: Pesquisa

      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true